*** Variables ***
${COMPANY_REQUESTED_TRIPS_AVAILABLE_BUTTON}            css=.x-btn.x-btn-primary.x-btn-sm

${COMPANY_REQUESTED_TRIPS_BID_INPUT}                   [name="Form.CarrierOfferAmount"]
${COMPANY_REQUESTED_TRIPS_CAR_DROPDOWN}                [name="Form.CarId"]
${COMPANY_REQUESTED_TRIPS_DRIVER_DROPDOWN}             [name="Form.CompanyDriverId"]
${COMPANY_REQUESTED_TRIPS_SAVE_BUTTON}                 "Save"
